name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: List files for debugging
      run: ls -al
    - name: Build the Docker image
      run: docker build ./ProjectBuckwheat.API --file ./ProjectBuckwheat.API/Dockerfile --tag my-image-name:$(date +%s)
